config/routes.rb
Rails.application.routes.draw do
  resources :notes
  get "note/:id/share" => "notes#share", :as => "share_note"
  root "application#welcome", :as => "home", via: :all
  post "note/shared" => "notes#shared", :as => "shared_note_update"
  delete "delete_note" => "notes#destroy", :as => "delete_note"
  get "signup" => "users#new", :as => "user_signup"
  post "user_create" => "users#create", :as => "user_create"
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  has_many :shared_note
end

app/models/shared_note.rb
class SharedNote < ApplicationRecord
  belongs_to :note
  validates :email, presence: true
  validates :role, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :password, :confirmation => true
  validates :name, presence: true
  validates :email, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize
  skip_before_action :authorize, only: [:welcome]

  def welcome
    if session[:user_id].present?
      redirect_to notes_path
    else
      render "layouts/welcome"
    end
  end

  protected
	def authorize
    unless User.find_by(id: session[:user_id])
      redirect_to login_url, notice: "Please Log in"
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:share, :shared]
  before_action :owner_access, only: [:destroy, :share]
  before_action :update_access, only: [:edit]
  before_action :read_access, only: [:show]

  def index
    @notes = Note.where(user_id: session[:user_id])
    email = User.find(session[:user_id]).email
    cn = SharedNote.where("email = ? AND role = ?", email, "Contributor")
    cn_ids = cn.pluck(:note_id) if cn.present?
    @contributer_access_notes = Note.where(id: cn_ids)
    rn = SharedNote.where("email = ? AND role = ?", email, "Reader")
    rn_ids = rn.pluck(:note_id) if rn.present?
    @reader_access_notes = Note.where(id: rn_ids)
  end

  def show
    @owner_access = is_owner?
    @update_access = @owner_access || can_update?
  end

  def new
    @note = Note.new
  end

  def share
    @note_id = params[:id].to_i
  end

  def shared
    if note = SharedNote.where("email = ? AND note_id = ?", params[:email], params[:note_id]).first
      note.role = params[:role]
      note.save
    else
      shared_note = SharedNote.new
      shared_note.email = params[:email]
      shared_note.note_id = params[:note_id]
      shared_note.role = params[:role]
      shared_note.save
    end
    redirect_to notes_url, notice: 'Note was successfully shared.'
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = session[:user_id]

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def owner_access
    redirect_to notes_url, notice: "You are not authorized for this operation" unless is_owner?
  end

  def update_access
    if !is_owner? && !can_update?
      redirect_to notes_url, notice: "You are not authorized for this operation"
    end
  end

  def read_access
    unless is_owner?
      email = User.find_by_id(session[:user_id]).email
      shared_note = SharedNote.where(note_id: params[:id], email: email).first
      redirect_to notes_url, notice: "You are not authorized for this operation" unless shared_note.present? && (shared_note.role.downcase == "contributor" || shared_note.role.downcase == "reader")
    end
  end

  def is_owner?
    Note.find(params[:id]).user_id == session[:user_id]
  end

  def can_update?
    email = User.find_by_id(session[:user_id]).email
    shared_note = SharedNote.where(note_id: params[:id], email: email).first
    shared_note.present? && shared_note.role.downcase == "contributor"
  end

  private
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :description, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :authorize
  
  def new
    @hide_sign_up = true
  end

  def create
    user = User.find_by_email(params[:email])
    if user.try(:authenticate, params[:password])
      session[:user_id] = user.id
      redirect_to notes_url
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_url, notice: "Logged Out"    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize

  def show
  end

  def new
    @user = User.new
    @hide_sign_up = true
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to notes_url, notice: 'Welcome to Notes Share' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors,
          status: :unprocessable_entity }
      end
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :password, :email, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css", :rel => "stylesheet"}/
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"}
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Notes Share
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', |
      'data-turbolinks-track': 'reload'                   
 
  %body
    .header_home.row
      .title_resize
        = link_to 'Notes Share', home_path
      - if session[:user_id]
        .header_right
          = button_to 'Logout', logout_path, method: :delete, class: 'btn btn-danger', id: "logout_button"
    - unless session[:user_id] || @hide_sign_up
      %nav.navbar.bg-light.signup_component
        %ul.navbar-nav
          %li.nav-item
            .nav-link 
              = button_to 'Sign Up', user_signup_path, method: :get, class: 'btn btn-outline-primary'
          %li.nav-item
            .nav-link.login_button 
              = button_to 'Sign In', login_url, method: :get, class: 'btn btn-outline-secondary'
    %main{:class => "#{controller.controller_name}"}
      = yield

app/views/notes/_form.html.haml
= form_with(model: note, local: true) do |form|
  - if note.errors.any?
    #error_explanation
      %h2
        = pluralize(note.errors.count, "error")
        prohibited this note from being saved:
      %ul
        - note.errors.full_messages.each do |message|
          %li= message
  %br
  .container
    .field.form-group
      = form.label :title
      = form.text_field :title, :class => "form-control"
    .field.form-group
      = form.label :description
      .input-group.mb-3.update_note_text_area
        = form.text_area :description, :class => "form-control"
    .actions
      = form.submit :class => "btn btn-success", :value => "Create"

app/views/notes/index.html.haml
%head
  = stylesheet_link_tag 'notes', media: 'all', |
      'data-turbolinks-track': 'reload'
- if notice.present?
  .alert.alert-success
    = notice
- if session[:user_id]
  %ul.nav.nav-tabs{:role => "tablist"}
    %li.nav-item
      %a.nav-link.active{"data-toggle" => "tab", :href => "#my_notes"} My Notes
    %li.nav-item
      %a.nav-link{"data-toggle" => "tab", :href => "#contributor_notes"} Contributed
    %li.nav-item
      %a.nav-link{"data-toggle" => "tab", :href => "#reader_notes"} Reader

.tab-content
  #my_notes.container.tab-pane.active
    %br/
    %ul.list-group
      - @notes.each do |note|   
        %li.list-group-item
          = link_to "#{note.title}", note

  #contributor_notes.container.tab-pane.fade
    %br/
    %ul.list-group
      - @contributer_access_notes.each do |note|   
        %li.list-group-item
          = link_to "#{note.title}", note
  #reader_notes.container.tab-pane.fade
    %br/
    %ul.list-group
      - @reader_access_notes.each do |note|   
        %li.list-group-item
          = link_to "#{note.title}", note
.container
  %br
  = link_to 'New', new_note_path, class: 'btn btn-success'

app/views/notes/new.html.haml
= render 'form', note: @note

app/views/notes/share.html.haml
= form_tag('/note/shared') do
  %br
  .container
    .field.form-group.input_field_small
      = label_tag :email, 'Email:'
      = text_field_tag :email, params[:email], :class => "form-control"
    .field.form-group
      = select_tag :role, raw("<option>Contributor</option><option>Reader</option>")
    = hidden_field_tag 'note_id', @note_id
    .actions
      = submit_tag "share", :class => "btn btn-success", :value => "Share"

app/views/notes/show.html.haml
- if notice.present?
  .alert.alert-success
    = notice
- if @note.errors.any?
  %ul
    - note.errors.full_messages.each do |message|
      %li= message
%br
.container
  = form_for @note, local: true, :url => {:action => "update", :id => @note} do |form|
    .field
      .input-group.mb-3.update_note_text_area
        = form.text_area :description, :class => "form-control", :value => @note.description
      - if @update_access
        .btn-group.btn-group-lg
          = form.submit :class => "btn_share", :value => "Update"
  - if @owner_access
    .align_show
      .btn-group.btn-group-lg
        = button_to 'Delete', @note, method: :delete, :class => 'btn btn-danger align_show_button'
      .btn-group.btn-group-lg.share_button
        = button_to 'Share', share_note_path, method: :get, :class => 'btn btn-secondary align_show_button'
      

app/views/users/new.html.haml
= form_for :user, local: true, :url => {:action => "create"} do |form|
  - if @user.errors.any?
    #error_explanation
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  %br
  .container.input_field_small
    .field.form-group
      = form.label :name, 'Name:'
      = form.text_field :name, id: :user_name, size: 40, :class => "form-control"
    .field.form-group
      = form.label :email, 'Email:'
      = form.text_field :email, id: :user_email, :class => "form-control"
    .field.form-group
      = form.label :password, 'Password:'
      = form.password_field :password, id: :user_password, size: 40, :class => "form-control"
    .field.form-group
      = form.label :password_confirmation, 'Confirm Password:'
      = form.password_field :password_confirmation, id: :user_password_confirmation, size: 40, :class => "form-control"
    .actions
      = form.submit :class => "btn btn-success", :value => "Create Account"